[build]
command = "npm run build"
publish = "public"

[dev]
command = "npm run dev"

# Set immutable caching for static files, because they have fingerprinted filenames
[[headers]]
    for = "/build/*"

    [headers.values]
        "Cache-Control" = "public, max-age=31560000, immutable"

[[headers]]
    for = "/assets/*"

    [headers.values]
        "Cache-Control" = "public, max-age=31560000, immutable"

[[headers]]
    for = "/favicons/*"

    [headers.values]
        "Cache-Control" = "public, max-age=31560000, immutable"
